# Site settings
title: "iCrazyBlaze's Blog"
email: icrazyblaze1@gmail.com
description: "My coding projects and videos"
baseurl: "/blog"
url: "http://icrazyblaze.github.io/"
title_description: "My blog for coding and tech."
title_image: "https://icrazyblaze.github.io/images/avatar.png"
google_analytics: 
disqus_account: icrazyblazeblog
github_repository: https://github.com/icrazyblaze/blog
addthis_id: ra-5d39ae2f608a7320
post_limit: 5

# Social usernames/URLs
twitter_username: crazy420blaze
github_username:  icrazyblaze
instagram_username: 
reddit_username: icrazyblaze
linkedin_link: 
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link:

# Footer
footer_left: "Made with <i class=\"fas fa-heart\"></i> by <a href=\"https://icrazyblaze.github.io\">iCrazyBlaze</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/icrazyblaze/carte-noire\">GitHub</a> &nbsp;<i class=\"fab fa-github\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
